---
# tasks file for java

# - name: Create a directory - java directory
#   file:
#     path: /usr/java
#     state: directory

# - name: Unarchive a java file that is already on the remote machine
#   unarchive:
#     src: files/jdk-8u221-linux-x64.tar.gz
#     dest: /usr/java/
#     remote_src: no
  

- name: add br_netfilter to k8s.conf
  shell: |
    cat <<EOF | sudo tee /etc/profile.d/java.sh
    export JAVA_HOME=/usr/java/jdk1.8.0_221
    export PATH=$PATH:$JAVA_HOME/bin
    export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
    EOF

- name: Execute /etc/profile.d/java.sh
  shell: source /etc/profile.d/java.sh

- name: update alternatives for java
  alternatives:
    name: java
    path: /usr/java/jdk1.8.0_221/bin/java
    link: /usr/bin/java
    priority: 1

- name: update alternatives for javac
  alternatives:
    name: javac
    path: /usr/java/jdk1.8.0_221/bin/javac
    link: /usr/bin/javac
    priority: 1

- name: Correct java version selected
  alternatives:
    name: java
    path: /usr/java/jdk1.8.0_221/bin/java